"""Shared configuration constants."""

# --- Screen ---
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# --- Agent ---
AGENT_RADIUS = 15
MAX_SPEED = 150  # pixels/sec
GOAL_THRESHOLD = 20

# --- RRT Planner ---
RRT_ITERATIONS = 500
RRT_STEP_SIZE = 25
RRT_GOAL_BIAS = 0.1
AVOIDANCE_RADIUS = AGENT_RADIUS * 2.5

# --- Communication ---
PREDICTION_HORIZON = 5.0
PREDICTION_DT = 0.1
COLLISION_DISTANCE = AGENT_RADIUS * 2.2
COMMUNICATION_TRIGGER_DISTANCE = 250
REPLAN_COOLDOWN_TIME = 1.5